# https://docs.docker.com/compose/

version: "3.9"

services:
    # Serves the website
    nginx:
        build: services/nginx
        container_name: nginx
        hostname: dda-silv.42.fr.com
        domainname: dda-silv.42.fr.com
        restart : always
        ports:
            - 443:443
        depends_on:
            - wordpress
    wordpress:
        build: services/wordpress
        container_name: wordpress
        restart : always
        expose:
            - 9000